Ingress:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      jtthink.ingress.kubernetes.io/add-request-header: name=shenyi;age=19
      jtthink.ingress.kubernetes.io/add-response-header: ret=ok
      jtthink.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: jtthink
    creationTimestamp: null
    name: ingress-myservicea
  spec:
    rules:
    - host: aabb.com
      http:
        paths:
        - backend:
            service:
              name: www.jtthink.com
              port:
                number: 80
          path: /jtthink/{param:.*}
          pathType: null
        - backend:
            service:
              name: www.baidu.com
              port:
                number: 80
          path: /baidu/{param:.*}
          pathType: null
        - backend:
            service:
              name: cloud.tencent.com
              port:
                number: 80
          path: /cccccc/{param:.*}
          pathType: null
  status:
    loadBalancer: {}
Server:
  Port: 0
